WebPro/Controllers/PhotoConsoleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPro.Models;

namespace WebPro.Controllers
{
    public class PhotoConsoleController : Controller
    {
        private WebEntities db = new WebEntities();

        //
        // GET: /PhotoConsole/

        public ActionResult Index()
        {
            return View(db.Photos.ToList());
        }

        //
        // GET: /PhotoConsole/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /PhotoConsole/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create(Photos photos)
        {
            if (ModelState.IsValid)
            {
                db.Photos.Add(photos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(photos);
        }

        //
        // GET: /PhotoConsole/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Photos photos = db.Photos.Find(id);
            if (photos == null)
            {
                return HttpNotFound();
            }
            return View(photos);
        }

        //
        // POST: /PhotoConsole/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit(Photos photos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(photos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(photos);
        }

        //
        // GET: /PhotoConsole/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Photos photos = db.Photos.Find(id);
            if (photos == null)
            {
                return HttpNotFound();
            }
            return View(photos);
        }

        //
        // POST: /PhotoConsole/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Photos photos = db.Photos.Find(id);
            db.Photos.Remove(photos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

WebPro/Views/PhotoConsole/Create.cshtml
@model WebPro.Models.Photos

@{
    ViewBag.Title = "Create";
}

<div class="content-side-right">
    <div class="container content-sm">
        <div class="post-comment">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(false)

                <fieldset>
                    <div class="headline">
                        <h3><i class="fa fa-pencil"></i>新增照片</h3>
                        &nbsp;
                        <a href="@Url.Action("Index")"><i class="fa  fa-reply"></i></a>
                    </div>

                    <div class="row margin-bottom-10">
                        <div class="col-md-7 col-md-offset-0">
                            <label>标题</label>
                            <input id="title" name="title" type="text" class="form-control" placeholder="title">
                            @Html.ValidationMessageFor(model => model.title)
                        </div>
                    </div>

                    <label>内容</label>
                    <div class="row margin-bottom-10">
                        <div class="col-md-11 col-md-offset-0">
                            <textarea id="content" name="content" class="form-control" rows="5" placeholder="content"></textarea>
                            @Html.ValidationMessageFor(model => model.content)
                        </div>
                    </div>


                    <div class="row margin-bottom-10">
                        <div class="col-md-4 col-md-offset-0">
                            <label>日期</label>
                            <input id="publishTime" name="publishTime" type="datetime" class="form-control">
                            @Html.ValidationMessageFor(model => model.publishTime)
                        </div>
                        <div class="col-md-3 col-md-offset-0">
                            <label>排序</label>
                            <input id="orderNum" name="orderNum" type="text" class="form-control" value="0">
                            @Html.ValidationMessageFor(model => model.orderNum)
                        </div>
                    </div>

                    <div class="row margin-bottom-10">
                        <div class="col-md-4 col-md-offset-0">
                            <label>照片路径</label>
                            <input id="imgurls" name="imgurls" type="text" class="form-control" placeholder="photo path">
                            @Html.ValidationMessageFor(model => model.imgurls)
                        </div>
                        <div class="col-md-4 col-md-offset-0">
                            <label>所属相册</label>
                            <input id="photoGroup" name="photoGroup" type="text" class="form-control" placeholder="album">
                            @Html.ValidationMessageFor(model => model.photoGroup)
                        </div>
                    </div>
                    <p>
                        <input type="submit" class="btn-u" value="确 认" />
                    </p>
                </fieldset>
            }
        </div>
    </div>
</div>
@section PageSpecificJavascriptIncludes{
    <script type="text/javascript" src="~/assets/plugins/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="~/assets/plugins/jquery/jquery-migrate.min.js"></script>
    <script type="text/javascript" src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <!-- JS Customization -->
    <script type="text/javascript" src="~/assets/js/custom.js" charset="gbk"></script>

    <script type="text/javascript" src="~/assets/plugins/back-to-top.js"></script>
    <script type="text/javascript" src="~/assets/plugins/jquery-appear.js"></script>
    <script type="text/javascript" src="~/assets/plugins/smoothScroll.js"></script>
    <!-- JS Page Level -->
    <script type="text/javascript" src="~/assets/js/app.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function () {
            App.init();
            $("#photopli").addClass("active");
            $("#photoli").addClass("active");
        });
    </script>
}

WebPro/Views/PhotoConsole/Delete.cshtml
@model WebPro.Models.Photos

@{
    ViewBag.Title = "Delete";
}

<div class="content-side-right">
    <div class="container content-sm">
        <div class="post-comment">
            <h3>确认删除?</h3>
            <fieldset>
                <div class="headline">
                    <h3>
                        <i class="fa fa-times"></i>删除照片--@Model.title
                    </h3>
                    &nbsp;
                    <a href="@Url.Action("Index")"><i class="fa  fa-reply"></i></a>
                </div>
            </fieldset>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <p>
                    <input type="submit" class="btn-u" value="确 认" />
                </p>
            }
        </div>
    </div>
</div>
@section PageSpecificJavascriptIncludes{
    <script type="text/javascript" src="~/assets/plugins/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="~/assets/plugins/jquery/jquery-migrate.min.js"></script>
    <script type="text/javascript" src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <!-- JS Customization -->
    <script type="text/javascript" src="~/assets/js/custom.js" charset="gbk"></script>

    <script type="text/javascript" src="~/assets/plugins/back-to-top.js"></script>
    <script type="text/javascript" src="~/assets/plugins/jquery-appear.js"></script>
    <script type="text/javascript" src="~/assets/plugins/smoothScroll.js"></script>
    <!-- JS Page Level -->
    <script type="text/javascript" src="~/assets/js/app.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function () {
            App.init();
            $("#photopli").addClass("active");
            $("#photoli").addClass("active");
        });
    </script>
}

WebPro/Views/PhotoConsole/Edit.cshtml
@model WebPro.Models.Photos

@{
    ViewBag.Title = "Edit";
}

<div class="content-side-right">
    <div class="container content-sm">
        <div class="post-comment">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(false)

                <fieldset>
                    <div class="headline">
                        <h3><i class="fa fa-pencil"></i>编辑照片--@Model.title</h3>
                        &nbsp;
                        <a href="@Url.Action("Index")"><i class="fa  fa-reply"></i></a>
                    </div>

                    @Html.HiddenFor(model => model.id)

                    <div class="row margin-bottom-10">
                        <div class="col-md-7 col-md-offset-0">
                            <label>标题</label>
                            <input id="title" name="title" type="text" class="form-control" value="@Model.title" placeholder="title">
                            @Html.ValidationMessageFor(model => model.title)
                        </div>
                    </div>

                    <label>内容</label>
                    <div class="row margin-bottom-10">
                        <div class="col-md-11 col-md-offset-0">
                            <textarea id="content" name="content" class="form-control" rows="5" placeholder="content">@Model.content</textarea>
                            @Html.ValidationMessageFor(model => model.content)
                        </div>
                    </div>


                    <div class="row margin-bottom-10">
                        <div class="col-md-4 col-md-offset-0">
                            <label>日期</label>
                            <input id="publishTime" name="publishTime" type="datetime" class="form-control" value="@Model.publishTime">
                            @Html.ValidationMessageFor(model => model.publishTime)
                        </div>
                        <div class="col-md-3 col-md-offset-0">
                            <label>排序</label>
                            <input id="orderNum" name="orderNum" type="text" class="form-control" value="@Model.orderNum">
                            @Html.ValidationMessageFor(model => model.orderNum)
                        </div>
                    </div>

                    <div class="row margin-bottom-10">
                        <div class="col-md-4 col-md-offset-0">
                            <label>照片路径</label>
                            <input id="imgurls" name="imgurls" type="text" class="form-control" value="@Model.imgurls" placeholder="photo path">
                            @Html.ValidationMessageFor(model => model.imgurls)
                        </div>
                        <div class="col-md-4 col-md-offset-0">
                            <label>所属相册</label>
                            <input id="photoGroup" name="photoGroup" type="text" class="form-control" value="@Model.photoGroup" placeholder="album">
                            @Html.ValidationMessageFor(model => model.photoGroup)
                        </div>
                    </div>
                    <p>
                        <input type="submit" class="btn-u" value="确 认" />
                    </p>
                </fieldset>
            }
        </div>
    </div>
</div>
@section PageSpecificJavascriptIncludes{
    <script type="text/javascript" src="~/assets/plugins/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="~/assets/plugins/jquery/jquery-migrate.min.js"></script>
    <script type="text/javascript" src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <!-- JS Customization -->
    <script type="text/javascript" src="~/assets/js/custom.js" charset="gbk"></script>

    <script type="text/javascript" src="~/assets/plugins/back-to-top.js"></script>
    <script type="text/javascript" src="~/assets/plugins/jquery-appear.js"></script>
    <script type="text/javascript" src="~/assets/plugins/smoothScroll.js"></script>
    <!-- JS Page Level -->
    <script type="text/javascript" src="~/assets/js/app.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function () {
            App.init();
            $("#photopli").addClass("active");
            $("#photoli").addClass("active");
        });
    </script>
}

WebPro/Views/PhotoConsole/Index.cshtml
@model IEnumerable<WebPro.Models.Photos>

@{
    ViewBag.Title = "Index";
}
@section PageSpecificStyleSheetIncludes{
    <link rel="stylesheet" href="~/assets/css/pages/blog.css">
    <link rel="stylesheet" href="~/assets/css/pages/blog_magazine.css">
}
<div class="content-side-right">
    <div class="container content-sm">
        @foreach (var item in Model)
        {
            <div class="row blog blog-medium margin-bottom-40">
                <div>
                    <h2>@item.title</h2>
                    <ul class="list-unstyled list-inline blog-info">
                        <li><i class="fa fa-calendar"></i> @item.publishTime.ToString("yyyy-MM-dd")</li>
                    </ul>
                    <p>@item.content</p>
                    <p>
                        <a class="btn-u btn-u-sm" href="@Url.Action("Create", "PhotoConsole")">新增 <i class="fa  fa-plus margin-left-5"></i></a>
                        <a class="btn-u btn-u-sm" href="@Url.Action("Edit", "PhotoConsole", new { id = @item.id }, null)">编辑 <i class="fa fa-pencil margin-left-5"></i></a>
                        <a class="btn-u btn-u-sm" href="@Url.Action("Delete", "PhotoConsole", new { id = @item.id }, null)">删除 <i class="fa fa-times margin-left-5"></i></a>
                    </p>
                </div>
            </div>
            <hr />
        }
    </div>
</div>
@section PageSpecificJavascriptIncludes{
    <script type="text/javascript" src="~/assets/plugins/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="~/assets/plugins/jquery/jquery-migrate.min.js"></script>
    <script type="text/javascript" src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <!-- JS Customization -->
    <script type="text/javascript" src="~/assets/js/custom.js" charset="gbk"></script>

    <script type="text/javascript" src="~/assets/plugins/back-to-top.js"></script>
    <script type="text/javascript" src="~/assets/plugins/jquery-appear.js"></script>
    <script type="text/javascript" src="~/assets/plugins/smoothScroll.js"></script>
    <!-- JS Page Level -->
    <script type="text/javascript" src="~/assets/js/app.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function () {
            App.init();
            $("#photopli").addClass("active");
            $("#photoli").addClass("active");
        });
    </script>
}