WebPro/Controllers/TimeConsoleController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPro.Models;

namespace WebPro.Controllers
{
    public class TimeConsoleController : Controller
    {
        private WebEntities db = new WebEntities();

        //
        // GET: /TimeConsole/

        public ActionResult Index()
        {
            return View(db.Essays.ToList());
        }

        public string GetData()
        {
            var pageSize = string.IsNullOrWhiteSpace(Request["limit"]) ? 10 : int.Parse(Request["limit"]);
            var offset = string.IsNullOrWhiteSpace(Request["offset"]) ? 0 : int.Parse(Request["offset"]);
            var sort = string.IsNullOrWhiteSpace(Request["sort"]) ? "id" : Request["sort"];
            var search = string.IsNullOrWhiteSpace(Request["search"]) ? "" : Request["search"];
            var order = string.IsNullOrWhiteSpace(Request["order"]) ? "asc" : Request["order"];

            var temp = from d in db.Essays
                       where d.title.Contains(search) || d.content.Contains(search)
                       select new { d.id, d.content, d.title, d.publishTime };
            //temp = temp.Skip(pageNum * pageSize).Take(pageSize);
            //temp = temp.Where(s => s.content.Contains(search));
            switch (sort)
            {
                case "title":
                    temp = order == "desc" ? temp.OrderByDescending(s => s.title) : temp.OrderBy(s => s.title);
                    break;
                case "content":
                    temp = order == "desc" ? temp.OrderByDescending(s => s.content) : temp.OrderBy(s => s.content);
                    break;
                case "publishTime":
                    temp = order == "desc" ? temp.OrderByDescending(s => s.publishTime) : temp.OrderBy(s => s.publishTime);
                    break;
                default:
                    temp = order == "desc" ? temp.OrderByDescending(s => s.id) : temp.OrderBy(s => s.id);
                    break;
            }
            return JsonConvert.SerializeObject(new { total = temp.Count(), rows = temp.Skip(offset).Take(pageSize).ToList() });
            //return temp.ToJson();
        }

        //public string GetData()
        //{
        //    var temp = from d in db.Essays
        //               orderby d.id
        //               select new { d.id, d.content, d.title, d.publishTime };
        //    return JsonConvert.SerializeObject(new { total = temp.Count(), rows = temp.ToList() });
        //    //return temp.ToJson();
        //}

        //
        // GET: /TimeConsole/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /TimeConsole/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create(Essays essays)
        {
            if (ModelState.IsValid)
            {
                var temp = db.Essays.Select(s => s.orderNum).Max();
                essays.orderNum = temp + 1;
                essays.publishTime = DateTime.Now;
                db.Essays.Add(essays);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(essays);
        }

        //
        // GET: /TimeConsole/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Essays essays = db.Essays.Find(id);
            if (essays == null)
            {
                return HttpNotFound();
            }
            string initialPreview = "";
            IList<InitialPreviewConfig> list = new List<InitialPreviewConfig>();
            if (!string.IsNullOrEmpty(essays.imgurls))
            {
                int i = 1;
                foreach (var img in essays.imgurls.Split(new char[] { '|' }, StringSplitOptions.RemoveEmptyEntries))
                {
                    list.Add(new InitialPreviewConfig(i, "/assets/ueditor/net/controller.ashx?action=deletefile", new DataExtra(img)));
                    initialPreview += "<img src='" + img + "' class='file-preview-image'>|";
                }
                initialPreview = initialPreview.Substring(0, initialPreview.Length - 1);
                i++;
            }
            ViewBag.initialPreview = initialPreview;
            ViewBag.initialPreviewConfig = JsonConvert.SerializeObject(list);
            return View(essays);
        }

        //
        // POST: /TimeConsole/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit(Essays essays)
        {
            if (ModelState.IsValid)
            {
                db.Entry(essays).State = EntityState.Modified;
                essays.publishTime = DateTime.Now;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(essays);
        }

        //
        // GET: /TimeConsole/Delete/5
        [HttpPost, ActionName("Delete")]
        public string Delete(int id = 0)
        {
            Essays essays = db.Essays.Find(id);
            if (essays == null)
            {
                return "F";
            }
            db.Essays.Remove(essays);
            db.SaveChanges();
            return "S";
        }

        //
        // POST: /TimeConsole/Delete/5

        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Essays essays = db.Essays.Find(id);
        //    db.Essays.Remove(essays);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

WebPro/Views/TimeConsole/Create.cshtml
@model WebPro.Models.Essays

@{
    ViewBag.Title = "时间碎片新增";
}

@section PageSpecificStyleSheetIncludes{
    <link href="~/assets/fileupload/css/fileinput.min.css" rel="stylesheet" type="text/css" />
}

<div class="content-side-right">
    <div class="container content-sm">
        <div class="post-comment">

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(false)

                <fieldset>
                    <div class="headline">
                        <h3><i class="fa fa-plus"></i>新增时间碎片</h3>
                        &nbsp;
                        <a href="@Url.Action("Index")"><i class="fa  fa-reply"></i></a>
                    </div>

                    <div class="row margin-bottom-10">
                        <div class="col-md-7 col-md-offset-0">
                            <label>标题</label>
                            <input id="title" name="title" type="text" class="form-control" placeholder="title">
                            @Html.ValidationMessageFor(model => model.title)
                        </div>
                        <div class="col-md-4 col-md-offset-0">
                            <label>星期</label>
                            <br />
                            <label class="select">
                                <select name="week" id="week" placeholder="week">
                                    <option selected value="Monday">Monday</option>
                                    <option value="Tuesday">Tuesday</option>
                                    <option value="Wednesday">Wednesday</option>
                                    <option value="Thursday">Thursday</option>
                                    <option value="Friday">Friday</option>
                                    <option value="Saturday">Saturday</option>
                                    <option value="Sunday">Sunday</option>
                                </select>
                            </label>
                            @Html.ValidationMessageFor(model => model.week)
                        </div>
                    </div>

                    <label>内容</label>
                    <div class="row margin-bottom-10">
                        <div class="col-md-11 col-md-offset-0">
                            <textarea id="content" name="content" class="form-control" rows="2" placeholder="content"></textarea>
                            @Html.ValidationMessageFor(model => model.content)
                        </div>
                    </div>

                    <div class="row margin-bottom-10">
                        <div class="col-md-11 col-md-offset-0">
                            <label>插图</label>
                            <div class="form-group">
                                <input id="images" name="upfile" class="file-loading" type="file" multiple data-show-upload="true">
                            </div>
                            <input id="imgurls" name="imgurls" type="text" class="form-control" placeholder="Illustration">
                            @Html.ValidationMessageFor(model => model.imgurls)
                        </div>
                    </div>


                    @*<div class="row margin-bottom-10">
                            <div class="col-md-4 col-md-offset-0">
                                <label>日期</label>
                                <input id="publishTime" name="publishTime" type="datetime-local" class="form-control">
                                @Html.ValidationMessageFor(model => model.publishTime)
                            </div>

                        </div>

                        <div class="row margin-bottom-10">
                            <div class="col-md-4 col-md-offset-0">
                                <label>插图</label>
                                <input id="imgurls" name="imgurls" type="text" class="form-control" placeholder="Illustration">
                                @Html.ValidationMessageFor(model => model.imgurls)
                            </div>
                            <div class="col-md-3 col-md-offset-0">
                                <label>排序</label>
                                <input id="orderNum" name="orderNum" type="text" class="form-control" value="0">
                                @Html.ValidationMessageFor(model => model.orderNum)
                            </div>
                        </div>*@

                    <p>
                        <input type="submit" class="btn-u" value="提 交" />
                    </p>
                </fieldset>
            }
        </div>
    </div>
</div>
@section PageSpecificJavascriptIncludes{
    <script type="text/javascript" src="~/assets/plugins/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="~/assets/plugins/jquery/jquery-migrate.min.js"></script>
    <script type="text/javascript" src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <!-- JS Customization -->
    <script type="text/javascript" src="~/assets/js/custom.js" charset="gbk"></script>

    <script type="text/javascript" src="~/assets/plugins/back-to-top.js"></script>
    <script type="text/javascript" src="~/assets/plugins/jquery-appear.js"></script>
    <script type="text/javascript" src="~/assets/plugins/smoothScroll.js"></script>
    <!-- JS Page Level -->
    <script type="text/javascript" src="~/assets/js/app.js"></script>

    <script src="~/assets/fileupload/js/fileinput.min.js" type="text/javascript"></script>
    <script src="~/assets/fileupload/js/fileinput_locale_zh.js" type="text/javascript"></script>

    @*<script type="text/javascript" src="~/assets/plugins/sky-forms-pro/skyforms/js/jquery-ui.min.js"></script>
        <script type="text/javascript" src="~/assets/plugins/sky-forms-pro/skyforms/js/jquery.validate.min.js"></script>
        <script type="text/javascript" src="~/assets/plugins/sky-forms-pro/skyforms/js/jquery.maskedinput.min.js"></script>
        <script type="text/javascript" src="~/assets/js/forms/checkout.js"></script>*@
    <script type="text/javascript">
        jQuery(document).ready(function () {
            App.init();
            $("#timeli").addClass("active");
            //BlogCheckForm.initBlogCheckForm();
        });

        $('#images').fileinput({
            language: 'zh', //设置语言
            uploadUrl: '/assets/ueditor/net/controller.ashx?action=uploadimage&sub=timeline', //上传的地址
            //allowedFileTypes: 'images',
            allowedFileExtensions: ['jpg', 'png', 'gif'],//接收的文件后缀
            showUpload: true, //是否显示上传按钮
            showCaption: true,//是否显示标题
            overwriteInitial: false,
            browseClass: "btn btn-primary", //按钮样式
            previewFileIcon: "<i class='glyphicon glyphicon-king'></i>",
        });

        $("#images").on("fileuploaded", function (event, data, previewId, index) {
            var da = data.response;
            var url = da.url;
            if ($("#imgurls").attr("value").length > 0)
                url = "|" + url;
            $("#imgurls").attr("value", $("#imgurls").attr("value") + url);
        });
    </script>
}

WebPro/Views/TimeConsole/Delete.cshtml
@model WebPro.Models.Essays

@{
    ViewBag.Title = "Delete";
}

<div class="content-side-right">
    <div class="container content-sm">
        <div class="post-comment">
            <h3>确认删除?</h3>
            <fieldset>
                <div class="headline">
                    <h3>
                        <i class="fa fa-times"></i>删除时间碎片--@Model.title
                    </h3>
                    &nbsp;
                    <a href="@Url.Action("Index")"><i class="fa  fa-reply"></i></a>
                </div>


            </fieldset>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <p>
                    <input type="submit" class="btn-u" value="确 认" />
                </p>
            }
        </div>
    </div>
</div>
@section PageSpecificJavascriptIncludes{
    <script type="text/javascript" src="~/assets/plugins/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="~/assets/plugins/jquery/jquery-migrate.min.js"></script>
    <script type="text/javascript" src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <!-- JS Customization -->
    <script type="text/javascript" src="~/assets/js/custom.js" charset="gbk"></script>

    <script type="text/javascript" src="~/assets/plugins/back-to-top.js"></script>
    <script type="text/javascript" src="~/assets/plugins/jquery-appear.js"></script>
    <script type="text/javascript" src="~/assets/plugins/smoothScroll.js"></script>
    <!-- JS Page Level -->
    <script type="text/javascript" src="~/assets/js/app.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function () {
            App.init();
            $("#timeli").addClass("active");
        });
    </script>
}

WebPro/Views/TimeConsole/Index.cshtml
@{
    ViewBag.Title = "时间轴维护";
}
@section PageSpecificStyleSheetIncludes{
    <link rel="stylesheet" href="~/assets/plugins/bootstrap/css/bootstrap-table.css">
}
<div class="content-side-right">
    <div class="container content-sm">
        <div id="toolbar">
            @*<button id="remove" class="btn btn-danger" disabled>
                    <i class="glyphicon glyphicon-remove"></i> Delete
                </button>*@
            <a class="btn-u btn-u-sm" href="@Url.Action("Create", "TimeConsole")">新增 <i class="fa  fa-plus margin-left-5"></i></a>
        </div>
        <table id="table"></table>
    </div>
</div>
@section PageSpecificJavascriptIncludes{
    <script type="text/javascript" src="~/assets/plugins/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/assets/plugins/bootstrap/js/bootstrap-table.js"></script>
    <script type="text/javascript" src="~/assets/plugins/bootstrap/js/bootstrap-table-zh-CN.js"></script>
    <script>
        jQuery(document).ready(function () {
            //App.init();
            $("#timeli").addClass("active");
            initTable();
        });
        var $table = $('#table'),
            //$remove = $('#remove'),
            selections = [];
        function initTable() {
            $table.bootstrapTable({
                url: '@Url.Action("GetData", "TimeConsole")',
                locale: 'zh',
                pagination: true,
                sidePagination: 'server',
                search: true,
                showHeader: true,
                showFooter: false,
                showColumns: true,
                showPaginationSwitch: true,
                showRefresh: true,
                showToggle: true,
                minimumCountColumns: 2,
                detailView: true,
                detailFormatter: detailFormatter,
                toolbar: '#toolbar',
                height: getHeight(),
                responseHandler: responseHandler,
                striped: true,
                clickToSelect: true,
                smartDisplay: true,
                columns: [
                        {
                            field: 'state',
                            checkbox: true,
                            align: 'center',
                            valign: 'middle'
                        }, {
                            title: 'ID',
                            field: 'id',
                            align: 'center',
                            valign: 'middle',
                            sortable: true
                        },
                         {
                             field: 'title',
                             title: '标题',
                             sortable: true,
                             align: 'left'
                             //editable: {
                             //    type: 'text',
                             //    title: 'Item Price',
                             //    validate: function (value) {
                             //        value = $.trim(value);
                             //        if (!value) {
                             //            return 'This field is required';
                             //        }
                             //        if (!/^$/.test(value)) {
                             //            return 'This field needs to start width $.'
                             //        }
                             //        var data = $table.bootstrapTable('getData'),
                             //            index = $(this).parents('tr').data('index');
                             //        console.log(data[index]);
                             //        return '';
                             //    }
                             //},
                             //footerFormatter: totalPriceFormatter
                         },
                        {
                            field: 'content',
                            title: '内容',
                            sortable: true,
                            //editable: true,
                            align: 'left'
                        }, {
                            field: 'publishTime',
                            title: '发布日期',
                            sortable: true,
                            align: 'center'
                        },
                        {
                            field: 'operate',
                            title: '操作',
                            align: 'center',
                            events: operateEvents,
                            formatter: operateFormatter
                        }
                ]
            });
            // sometimes footer render error.
            setTimeout(function () {
                $table.bootstrapTable('resetView');
            }, 200);
            $table.on('check.bs.table uncheck.bs.table ' +
                    'check-all.bs.table uncheck-all.bs.table', function () {
                        $remove.prop('disabled', !$table.bootstrapTable('getSelections').length);
                        // save your data, here just save the current page
                        selections = getIdSelections();
                        // push or splice the selections if you want to save all data selections
                    });
            $table.on('expand-row.bs.table', function (e, index, row, $detail) {
                if (index % 2 == 1) {
                    $detail.html('Loading from ajax request...');
                    $.get('LICENSE', function (res) {
                        $detail.html(res.replace(/\n/g, '<br>'));
                    });
                }
            });
            $table.on('all.bs.table', function (e, name, args) {
                console.log(name, args);
            });
            //$remove.click(function () {
            //    var ids = getIdSelections();
            //    $table.bootstrapTable('remove', {
            //        field: 'id',
            //        values: ids
            //    });
            //    $remove.prop('disabled', true);
            //});
            $(window).resize(function () {
                $table.bootstrapTable('resetView', {
                    height: getHeight()
                });
            });
        }
        function getIdSelections() {
            return $.map($table.bootstrapTable('getSelections'), function (row) {
                return row.id
            });
        }
        function responseHandler(res) {
            $.each(res.rows, function (i, row) {
                row.state = $.inArray(row.id, selections) !== -1;
            });
            return res;
        }
        function detailFormatter(index, row) {
            var html = [];
            $.each(row, function (key, value) {
                html.push('<p><b>' + key + ':</b> ' + value + '</p>');
            });
            return html.join('');
        }
        function operateFormatter(value, row, index) {
            return [
                '<a class="like" href="/TimeConsole/Edit/' + row.id, '" title="编辑">',
                '<i class="fa  fa-pencil"></i>',
                '</a>  ',
                '<a class="remove" href="javascript:void(0)" title="删除">',
                '<i class="glyphicon glyphicon-remove"></i>',
                '</a>'
            ].join('');
        }
        window.operateEvents = {
            //'click .like': function (e, value, row, index) {
            //    $.ajax({
            //        url: "/TimeConsole/Edit",
            //        type: "GET",
            //        dataType: "json",
            //        data: { id: row.id },
            //        success: function (res) {
            //        }
            //    });
            //},
            'click .remove': function (e, value, row, index) {
                if (confirm('您确认想要删除记录吗？')) {
                    $.ajax({
                        url: "/TimeConsole/Delete",
                        type: "POST",
                        data: { id: row.id },
                        success: function (res) {
                            if (res == "S") {
                                alert("删除成功!");
                                $table.bootstrapTable('refresh');
                            }
                        }
                    });
                }
            }
        };
        //function totalTextFormatter(data) {
        //    return 'Total';
        //}
        //function totalNameFormatter(data) {
        //    return data.length;
        //}
        //function totalPriceFormatter(data) {
        //    var total = 0;
        //    $.each(data, function (i, row) {
        //        total += +(row.price.substring(1));
        //    });
        //    return '$' + total;
        //}
        function getHeight() {
            return $(window).height() - $('h1').outerHeight(true);
        }
    </script>
}