WebPro/Models/Blogs.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blogs
    {
        public int id { get; set; }
        public string title { get; set; }
        public string keyword { get; set; }
        public string showContent { get; set; }
        public string content { get; set; }
        public string imgurls { get; set; }
        public System.DateTime publishTime { get; set; }
        public string author { get; set; }
        public int viewCount { get; set; }
        public int orderNum { get; set; }
        public int sourceId { get; set; }
    }
}

WebPro/Controllers/AboutMeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPro.Models;

namespace WebPro.Controllers
{
    public class AboutMeController : Controller
    {
        //
        // GET: /AboutMe/

        public ActionResult Index()
        {
            ViewBag.skin = GlobalVar.skin;
            return View();
        }

    }
}

WebPro/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPro.Models;

namespace WebPro.Controllers
{
    public class BlogController : Controller
    {
        private WebEntities db = new WebEntities();

        //
        // GET: /Blog/

        public ActionResult Index(int pageIndex = 1, string searchKey = "", int searchFlag = 0)
        {
            ViewBag.skin = GlobalVar.skin;
            int pageSize = (searchFlag != 0 ? 99999 : 5);
            //从数据库在取得数据，并返回总记录数
            var temp = from d in db.Blogs
                       where (searchFlag==0?1==1:(searchFlag == 1 ? d.keyword.Contains(searchKey) : d.title.Contains(searchKey) || d.keyword.Contains(searchKey) ||
                       d.author.Contains(searchKey) || d.content.Contains(searchKey)))
                       orderby d.id descending
                       select d;
            int count = temp.Count();
            var tag = from d in db.Blogs
                      select d.keyword;
            List<string> list = new List<string>();
            foreach (var item in tag)
            {
                list.AddRange(item.Split('|'));
            }
            var best = from d in db.Blogs
                       orderby d.viewCount descending
                       select d;
            BlogRight<IEnumerable<string>, IQueryable<Blogs>> blogright =
                new BlogRight<IEnumerable<string>, IQueryable<Blogs>>(list.Distinct<string>(), best.Take(5));
            PagerInfo pager = new PagerInfo();
            pager.CurrentPageIndex = pageIndex;
            pager.PageSize = pageSize;
            pager.RecordCount = count;
            PagerQuery<PagerInfo, IQueryable<Blogs>, BlogRight<IEnumerable<string>, IQueryable<Blogs>>> query
                = new PagerQuery<PagerInfo, IQueryable<Blogs>, BlogRight<IEnumerable<string>,
                    IQueryable<Blogs>>>(pager, temp.Skip<Blogs>((pageIndex - 1) * pageSize).Take<Blogs>(pageSize), blogright);
            return View(query);
        }

        //public ActionResult Search(string searchKey = "", int pageIndex = 1)
        //{
        //    searchKey=searchKey.ToUpper();
        //    int pageSize = 3;
        //    //从数据库在取得数据，并返回总记录数
        //    var temp = from d in db.Blogs
        //               select d;
        //    temp = temp.Where<Blog>(s => s.title.Contains(searchKey) || s.content.Contains(searchKey) ||
        //        s.author.Contains(searchKey) || s.keyword.Contains(searchKey));
        //    int count = temp.Count();
        //    var tag = from d in db.Blogs
        //              select d.keyword;
        //    List<string> list = new List<string>();
        //    foreach (var item in tag)
        //    {
        //        list.AddRange(item.Split('|'));
        //    }
        //    var best = from d in db.Blogs
        //               orderby d.viewCount descending
        //               select d;
        //    BlogRight<IEnumerable<string>, IQueryable<Blog>> blogright =
        //        new BlogRight<IEnumerable<string>, IQueryable<Blog>>(list.Distinct<string>(), best.Take(5));
        //    PagerInfo pager = new PagerInfo();
        //    pager.CurrentPageIndex = pageIndex;
        //    pager.PageSize = pageSize;
        //    pager.RecordCount = count;
        //    PagerQuery<PagerInfo, IQueryable<Blog>, BlogRight<IEnumerable<string>, IQueryable<Blog>>> query
        //        = new PagerQuery<PagerInfo, IQueryable<Blog>, BlogRight<IEnumerable<string>,
        //            IQueryable<Blog>>>(pager, temp.OrderByDescending(s => s.publishTime).Skip<Blog>((pageIndex - 1) * pageSize).Take<Blog>(pageSize), blogright);
        //    return View("Index",query);
        //}

        //
        // GET: /Blog/Details/5

        public ActionResult Details(int id = 0)
        {
            ViewBag.skin = GlobalVar.skin;
            Blogs blog = db.Blogs.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            Blogs before = db.Blogs.Where(s => s.id < id).OrderByDescending(s => s.id).FirstOrDefault();
            Blogs after = db.Blogs.Where(s => s.id > id).OrderBy(s => s.id).FirstOrDefault();
            before = (before == null ? blog : before);
            after = (after == null ? blog : after);
            blog.viewCount += 1;
            db.Entry(blog).State = EntityState.Modified;
            db.SaveChanges();

            List<Blogs> blogs = new List<Blogs>();
            blogs.Add(blog);
            blogs.Add(before);
            blogs.Add(after);
            var tag = from d in db.Blogs
                      select d.keyword;
            List<string> list = new List<string>();
            foreach (var item in tag)
            {
                list.AddRange(item.Split('|'));
            }
            var best = from d in db.Blogs
                       orderby d.viewCount descending
                       select d;
            BlogRight<IEnumerable<string>, IQueryable<Blogs>> blogright =
                new BlogRight<IEnumerable<string>, IQueryable<Blogs>>(list.Distinct<string>(), best.Take(5));
            DetailQuery<List<Blogs>, BlogRight<IEnumerable<string>, IQueryable<Blogs>>> query
                = new DetailQuery<List<Blogs>, BlogRight<IEnumerable<string>,
                    IQueryable<Blogs>>>(blogs, blogright);
            return View(query);
        }
    }
}

WebPro/Views/Blog/Details.cshtml
@model WebPro.Models.DetailQuery<List<WebPro.Models.Blogs>, WebPro.Models.BlogRight<IEnumerable<string>, IQueryable<WebPro.Models.Blogs>>>

@{
    ViewBag.Title = @Model.Blogs[0].title+"-左瑞祥的个人博客-可以平凡不能平庸";
}
@section metas{
    <meta name="description" content="@Model.Blogs[0].title-左瑞祥的个人博客">
    <meta name="keywords" content="@Model.Blogs[0].keyword.Replace('|', ','),左瑞祥,个人博客">
}
@section PageSpecificStyleSheetIncludes{
    <link rel="stylesheet" href="~/assets/css/pages/blog.css">
    <link rel="stylesheet" href="~/assets/css/code/shCoreDefault.css">
}
<!--=== Breadcrumbs ===-->
<div class="breadcrumbs">
    <div class="container">
        <h5 class="pull-left" style="color:silver">再长的路，一步步也能走完，再短的路，不迈开双脚也无法到达。</h5>
        <ul class="pull-right breadcrumb">
            <li><i class="fa  fa-map-marker"></i> @Html.ActionLink("主页", "Index", "Home")</li>
            <li>@Html.ActionLink("程序人生", "Index", "Blog")</li>
            <li class="active">@Model.Blogs[0].title</li>
        </ul>
    </div>
</div><!--/breadcrumbs-->
<!--=== End Breadcrumbs ===-->
<!--=== Content Part ===-->
<div class="container content">
    <div class="row blog-page blog-item">
        <!-- Left Sidebar -->
        <div class="col-md-9 md-margin-bottom-60">
            <!--Blog Post-->
            <div class="blog margin-bottom-40">
                <h2>@Html.ActionLink(@Model.Blogs[0].title, "Details", "Blog", new { id = @Model.Blogs[0].id }, null)</h2>
                <div class="blog-post-tags">
                    <ul class="list-unstyled list-inline blog-info">
                        <li><i class="fa fa-calendar"></i> @Model.Blogs[0].publishTime.ToString("yyyy-MM-dd")</li>
                        <li><i class="fa fa-pencil"></i> @Html.ActionLink(@Model.Blogs[0].author, "Index", "AboutMe")</li>
                        <li><i class="fa fa-comments"></i> @Model.Blogs[0].viewCount.ToString() 阅读</li>
                    </ul>
                    <ul class="list-unstyled list-inline blog-tags">
                        <li>
                            <i class="fa fa-tags"></i>
                            @foreach (var key in Model.Blogs[0].keyword.Split(new char[] { '|' }, StringSplitOptions.RemoveEmptyEntries))
                            {
                                @Html.ActionLink(@key, "Index", "Blog", new { searchKey = @key, searchFlag = 1 }, null)
                            }
                        </li>
                    </ul>
                </div>
                @*<div class="tag-box tag-box-v2">
                        <p>Et harum quidem rerum facilis est et expedita distinctio lorem ipsum dolor sit amet consectetur adipiscing elit. Fusce condimentum eleifend enim a feugiatt non libero consectetur adipiscing elit magna. Sed et quam lacus. Condimentum eleifend enim a feugiat. Pellentesque viverra vehicula sem ut volutpat.</p>
                    </div>*@
                @Html.Raw(@Model.Blogs[0].content)
                @if (!string.IsNullOrEmpty(@Model.Blogs[0].sourceId.ToString()) && @Model.Blogs[0].sourceId != 0)
                {
                    <br><p>本文相关代码可前往以下链接获取：</p><br>
                    @Html.ActionLink("示例代码", "Index", "SourceCode", new { searchId = @Model.Blogs[0].sourceId, searchFlag = 2 }, null)
                }
            </div>
            <!--End Blog Post-->

            <hr>
            <div class="blog-twitter">
                <div class=" blog-twitter-inner">
                    <span><i class="fa  fa-reply"></i>上一篇：@Html.ActionLink((@Model.Blogs[1].title + (@Model.Blogs[1].id == Model.Blogs[0].id ? "(这是最新一篇)" : "")), "Details", "Blog", new { id = @Model.Blogs[1].id }, null)</span>
                    <br />
                    <span><i class="fa  fa-share"></i>下一篇：@Html.ActionLink((@Model.Blogs[2].title + (@Model.Blogs[2].id == Model.Blogs[0].id ? "(这是最后一篇)" : "")), "Details", "Blog", new { id = @Model.Blogs[2].id }, null)</span>
                </div>
            </div>
            <hr>
            <div class="bdsharebuttonbox"><a href="#" class="bds_more" data-cmd="more"></a><a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a><a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a><a href="#" class="bds_tqq" data-cmd="tqq" title="分享到腾讯微博"></a><a href="#" class="bds_renren" data-cmd="renren" title="分享到人人网"></a><a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信"></a></div>
            <script>window._bd_share_config = { "common": { "bdSnsKey": {}, "bdText": "", "bdMini": "2", "bdMiniList": false, "bdPic": "", "bdStyle": "0", "bdSize": "32" }, "share": {}, "image": { "viewList": ["qzone", "tsina", "tqq", "renren", "weixin"], "viewText": "分享到：", "viewSize": "24" }, "selectShare": { "bdContainerClass": null, "bdSelectMiniList": ["qzone", "tsina", "tqq", "renren", "weixin"] } }; with (document) 0[(getElementsByTagName('head')[0] || body).appendChild(createElement('script')).src = 'http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion=' + ~(-new Date() / 36e5)];</script>
            <hr>
            @*<div class="ds-share" data-thread-key="@Model.Blogs[0].id" data-title="@Model.Blogs[0].title">
                    <div class="ds-share-inline">
                        <ul class="ds-share-icons-16">

                            <li data-toggle="ds-share-icons-more"><a class="ds-more" href="javascript:void(0);">分享到：</a></li>

                            <li> <a class="ds-weibo" href="javascript:void(0);" data-service="weibo">新浪微博</a> </li>

                            <li> <a class="ds-qzone" href="javascript:void(0);" data-service="qzone">QQ空间</a> </li>

                            <li> <a class="ds-qqt" href="javascript:void(0);" data-service="qqt">腾讯微博</a> </li>

                            <li> <a class="ds-wechat" href="javascript:void(0);" data-service="wechat">微信</a> </li>
                        </ul>
                    </div>
                    <div class="ds-share-icons-more">

                    </div>
                </div>*@
            <!--PC版-->
            <div id="SOHUCS" sid="@Model.Blogs[0].id"></div>
            <script charset="utf-8" type="text/javascript" src="https://changyan.sohu.com/upload/changyan.js"></script>
            <script type="text/javascript">
                window.changyan.api.config({
                    appid: 'cyt66qHra',
                    conf: 'prod_3864f0bc4abb3b5125c9943aeb9e0b02'
                });
            </script>
        </div>
        <!-- End Left Sidebar -->
        @Html.Partial("RightShare", Model.BlogRight)
    </div><!--/row-->
</div><!--/container-->
<!--=== End Content Part ===-->
<!--=== End Content Part ===-->
<!-- JS Global Compulsory -->
@section PageSpecificJavascriptIncludes{
    <script type="text/javascript" src="~/assets/plugins/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="~/assets/plugins/jquery/jquery-migrate.min.js"></script>
    <script type="text/javascript" src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <!-- JS Implementing Plugins -->
    <script type="text/javascript" src="~/assets/plugins/back-to-top.js"></script>
    <script type="text/javascript" src="~/assets/plugins/smoothScroll.js"></script>

    <script type="text/javascript" src="~/assets/js/code/shCore.js"></script>
    <script type="text/javascript" src="~/assets/js/code/shBrushJScript.js"></script>
    <script type="text/javascript" src="~/assets/js/code/shBrushCSharp.js"></script>
    <script type="text/javascript" src="~/assets/js/code/shBrushPhp.js"></script>
    <script type="text/javascript" src="~/assets/js/code/shBrushCpp.js"></script>
    <script type="text/javascript" src="~/assets/js/code/shBrushJava.js"></script>
    <script type="text/javascript" src="~/assets/js/code/shBrushPython.js"></script>
	<script type="text/javascript" src="~/assets/js/code/shBrushSql.js"></script>
    <script type="text/javascript" src="~/assets/js/code/shBrushXml.js"></script>
    <!-- JS Customization -->
    <script type="text/javascript" src="~/assets/js/custom.js" charset="gbk"></script>
    <!-- JS Page Level -->
    <script type="text/javascript" src="~/assets/js/app.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function () {
            $("#blogli").addClass("active");
            App.init();
            SyntaxHighlighter.all();
        });
    </script>
}

WebPro/Views/Blog/Index.cshtml
@model WebPro.Models.PagerQuery<WebPro.Models.PagerInfo, IQueryable<WebPro.Models.Blogs>, WebPro.Models.BlogRight<IEnumerable<string>, IQueryable<WebPro.Models.Blogs>>>

@{
    ViewBag.Title = "程序人生-左瑞祥的个人博客-可以平凡不能平庸";
}
@section metas{
    <meta name="description" content="程序人生-左瑞祥的个人博客">
    <meta name="keywords" content="程序人生，左瑞祥，个人博客">
}
@using WebPro
@section PageSpecificStyleSheetIncludes{
    <link rel="stylesheet" href="~/assets/css/pages/blog.css">
    <link rel="stylesheet" href="~/assets/css/pages/blog_magazine.css">
}
<!--=== Breadcrumbs ===-->
<div class="breadcrumbs">
    <div class="container">
        <h5 class="pull-left" style="color:silver">平凡的脚步也可以走完伟大的行程。</h5>
        <ul class="pull-right breadcrumb">
            <li><i class="fa  fa-map-marker"></i> @Html.ActionLink("主页", "Index", "Home")</li>
            <li class="active">程序人生</li>
        </ul>
    </div>
</div><!--/breadcrumbs-->
<!--=== End Breadcrumbs ===-->
<!--=== Content Part ===-->
<div class="container content">
    <div class="row blog-page">
        <!-- Left Sidebar -->
        <div class="col-md-9">
            <!--Blog Post-->
            @foreach (var item in Model.EntityList)
            {
                <!--Blog Post-->
                <div class="row blog blog-medium margin-bottom-40">
                    <div class="col-md-5">
                        <div class="carousel slide carousel-v1" id="myCarousel_@item.id">
                            @if (item.imgurls != null && !string.IsNullOrEmpty(item.imgurls.Trim()))
                            {
                                <div class="carousel-inner">
                                    @foreach (var img in item.imgurls.Split(new char[] { '|' }, StringSplitOptions.RemoveEmptyEntries))
                                    {
                                        <div class="item">
                                            <img alt="" src="@img">
                                        </div>
                                    }
                                </div>

                                if (item.imgurls.Split(new char[] { '|' }, StringSplitOptions.RemoveEmptyEntries).Count() > 1)
                                {
                                    <div class="carousel-arrow">
                                        <a data-slide="prev" href="#myCarousel_@item.id" class="left carousel-control">
                                            <i class="fa fa-angle-left"></i>
                                        </a>
                                        <a data-slide="next" href="#myCarousel_@item.id" class="right carousel-control">
                                            <i class="fa fa-angle-right"></i>
                                        </a>
                                    </div>
                                }
                            }

                        </div>
                    </div>
                    <div class="col-md-7">
                        <h2>@Html.ActionLink(@item.title, "Details", "Blog", new { id = @item.id }, null)</h2>
                        <ul class="list-unstyled list-inline blog-info">
                            <li><i class="fa fa-calendar"></i> @item.publishTime.ToString("yyyy-MM-dd")</li>
                            <li><i class="fa fa-pencil"></i> @Html.ActionLink(@item.author, "Index", "AboutMe")</li>
                            <li id="downLi_@item.id"><i class="fa fa-comments"></i> @item.viewCount.ToString() 阅读</li>
                        </ul>
                        <ul class="list-unstyled list-inline blog-tags">
                            <li>
                                <i class="fa fa-tags"></i>
                                @foreach (var key in item.keyword.Split(new char[] { '|' }, StringSplitOptions.RemoveEmptyEntries))
                                {
                                    @Html.ActionLink(@key, "Index", "Blog", new { searchKey = @key, searchFlag = 1 }, null)
                                }
                            </li>
                        </ul>
                        <p>@item.showContent</p>
                        <p>
                            <a class="btn-u btn-u-sm" href="@Url.Action("Details", "Blog", new { id = @item.id },null)">详细信息 <i class="fa fa-angle-double-right margin-left-5"></i></a>
                        </p>
                    </div>
                </div>
                <hr class="margin-bottom-40">
            }
            <!--End Blog Post-->
            <!--Pagination-->
            <div class="text-center">
                <ul class="pagination">
                    @Html.ShowPageNavigate(Model.Pager.CurrentPageIndex, Model.Pager.PageSize, Model.Pager.RecordCount)
                </ul>
            </div>
            <!--End Pagination-->
        </div>
        <!-- End Left Sidebar -->
        @Html.Partial("RightShare", Model.BlogRight)
    </div><!--/row-->
</div><!--/container-->
<!--=== End Content Part ===-->
@section PageSpecificJavascriptIncludes{
    <script type="text/javascript" src="~/assets/plugins/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="~/assets/plugins/jquery/jquery-migrate.min.js"></script>
    <script type="text/javascript" src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <!-- JS Implementing Plugins -->
    <script type="text/javascript" src="~/assets/plugins/back-to-top.js"></script>
    <script type="text/javascript" src="~/assets/plugins/smoothScroll.js"></script>
    <!-- JS Customization -->
    <script type="text/javascript" src="~/assets/js/custom.js" charset="gbk"></script>
    <!-- JS Page Level -->
    <script type="text/javascript" src="~/assets/js/app.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function () {
            App.init();
            $("#blogli").addClass("active");
            $(".carousel-inner div.item:nth-child(1)").addClass("active");
        });
    </script>
}

WebPro/Views/Blog/RightShare.cshtml
@model WebPro.Models.BlogRight<IEnumerable<string>, IQueryable<WebPro.Models.Blogs>>
<!-- Right Sidebar -->
<div class="col-md-3 magazine-page">
    <!-- Search Bar -->
    <div class="headline headline-md"><h2>文本检索</h2></div>
    @using (Html.BeginForm("Index", "Blog", FormMethod.Get))
    {
        <div class="input-group margin-bottom-40">
            <input id="searchKey" name="searchKey" type="text" class="form-control" placeholder="Search">
            @Html.Hidden("searchFlag", 2)
            <span class="input-group-btn">
                <input class="btn-u" type="submit" value="Go" />
            </span>
        </div>
    }

    <!-- End Search Bar -->
    <!-- Blog Tags -->
    <div class="headline headline-md"><h2>标签检索</h2></div>
    <ul class="list-unstyled blog-tags margin-bottom-30">
        @foreach (var item in Model.Tag)
        {
            <li>
                <a href="@Url.Action("Index", "Blog", new { searchKey = @item, searchFlag=1 }, null)"><i class='fa fa-tags'></i> @item</a>
            </li>
        }
    </ul>
    <!-- End Blog Tags -->
    <!-- Posts -->
    <div class="blog-twitter margin-bottom-40">
        <div class="headline headline-md"><h2>点击排行</h2></div>
        @foreach (var item in Model.Best)
        {
            <div class="blog-twitter-inner">
                <i class="fa fa-twitter"></i>
                @Html.ActionLink(item.title, "Details", "Blog", new { id = @item.id }, null)
                <br />
                <p style="font-size:10px"><i class="fa fa-heart"></i>&nbsp;@item.keyword.Replace('|', '&') &nbsp;<i class="fa fa-comments"></i>&nbsp;@item.viewCount</p>
            </div>
        }
    </div><!--/posts-->
    <!-- End Posts -->
</div>
<!-- End Right Sidebar -->